// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function SetWindowState(arg1) {
  return window['go']['main']['App']['SetWindowState'](arg1);
}
