// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAgent'](arg1, arg2, arg3, arg4);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAppSetting(arg1) {
  return window['go']['main']['App']['GetAppSetting'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function ListAgents(arg1) {
  return window['go']['main']['App']['ListAgents'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function PauseSession(arg1) {
  return window['go']['main']['App']['PauseSession'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetAppSetting(arg1, arg2) {
  return window['go']['main']['App']['SetAppSetting'](arg1, arg2);
}

export function SetWindowState(arg1) {
  return window['go']['main']['App']['SetWindowState'](arg1);
}

export function UpdateAgent(arg1) {
  return window['go']['main']['App']['UpdateAgent'](arg1);
}
