// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {agent} from '../models';
import {model} from '../models';

export function CreateAgent(arg1:string,arg2:string,arg3:string,arg4:main.agentParams):Promise<agent.Agent>;

export function CreateSession(arg1:string):Promise<agent.Session>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetAgent(arg1:string):Promise<agent.Agent>;

export function GetAppSetting(arg1:string):Promise<string>;

export function GetSession(arg1:string):Promise<agent.Session>;

export function GetStatus():Promise<string>;

export function GetVersion():Promise<string>;

export function GetWindowState():Promise<string>;

export function ListAgents(arg1:main.listAgentsFilter):Promise<Array<agent.Agent>>;

export function ListModels(arg1:string):Promise<Array<model.ModelInfo>>;

export function ListProviders():Promise<Array<main.providerInfo>>;

export function ListSessions(arg1:main.listSessionsFilter):Promise<Array<agent.Session>>;

export function PauseSession(arg1:string):Promise<void>;

export function ResumeSession(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<agent.TurnResult>;

export function SetAppSetting(arg1:string,arg2:string):Promise<void>;

export function SetWindowState(arg1:string):Promise<void>;

export function UpdateAgent(arg1:agent.Agent):Promise<void>;
